# Generated by Django 5.0.4 on 2024-06-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('seller', '0003_location_alter_landlisting_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandListing',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
